start:
	npm run dev

build:
	npm run build

lint:
	npm run lint

test:
	npm run test

deploy:
	npm run deploy

add:
	git add .
	git status

check:
	git status
	git branch

anvay:
	git push origin anvay

main:
	git checkout main
	git branch
	git pull
	git checkout anvay