-- Snowflake DDL for Tunnel AI Backend
-- Run these commands in your Snowflake environment

-- Set context (adjust if your names differ)
USE WAREHOUSE NEXUS_WH;
USE DATABASE NEXUS_DB;
USE SCHEMA NEXUS_SC;

-- Create SESSIONS table
CREATE TABLE IF NOT EXISTS SESSIONS (
    ID INTEGER IDENTITY PRIMARY KEY,
    PRODUCT_IDEA TEXT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'processing',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create ANALYSIS_RESULTS table
CREATE TABLE IF NOT EXISTS ANALYSIS_RESULTS (
    ID INTEGER IDENTITY PRIMARY KEY,
    SESSION_ID INTEGER NOT NULL,
    PERSONAS TEXT, -- JSON string
    OPINIONS TEXT, -- JSON string
    SUMMARY TEXT,
    SENTIMENT_BREAKDOWN TEXT, -- JSON string
    MARKET_POTENTIAL VARCHAR(50),
    CONFIDENCE_SCORE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS(ID)
);

-- Create ELEVENLABS_AGENTS table for voice consultation
CREATE TABLE IF NOT EXISTS ELEVENLABS_AGENTS (
    ID INTEGER IDENTITY PRIMARY KEY,
    PERSONA_ID VARCHAR(50) NOT NULL UNIQUE,
    AGENT_ID VARCHAR(100) NOT NULL,
    PERSONA_NAME VARCHAR(200) NOT NULL,
    PERSONA_TITLE VARCHAR(200),
    PERSONA_LOCATION VARCHAR(200),
    PERSONA_INDUSTRY VARCHAR(200),
    SYSTEM_PROMPT TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create VOICE_CONSULTATIONS table
CREATE TABLE IF NOT EXISTS VOICE_CONSULTATIONS (
    ID INTEGER IDENTITY PRIMARY KEY,
    SESSION_ID INTEGER,
    AGENT_TABLE_ID INTEGER NOT NULL,
    CONVERSATION_ID VARCHAR(100),
    PERSONA_ID VARCHAR(50) NOT NULL,
    STARTUP_IDEA TEXT,
    DURATION_SECONDS FLOAT,
    TRANSCRIPT TEXT,
    STATUS VARCHAR(20) DEFAULT 'active',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ENDED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS(ID),
    FOREIGN KEY (AGENT_TABLE_ID) REFERENCES ELEVENLABS_AGENTS(ID)
);

-- Note: Standard Snowflake tables do not support CREATE INDEX.
-- For performance tuning, consider CLUSTER BY, e.g.:
-- ALTER TABLE SESSIONS CLUSTER BY (CREATED_AT);
-- ALTER TABLE ANALYSIS_RESULTS CLUSTER BY (SESSION_ID, CREATED_AT);
-- ALTER TABLE ELEVENLABS_AGENTS CLUSTER BY (PERSONA_ID);
-- ALTER TABLE VOICE_CONSULTATIONS CLUSTER BY (CREATED_AT, PERSONA_ID);
