-- Snowflake DDL for Tunnel AI Backend
-- Run these commands in your Snowflake environment

-- Set context (adjust if your names differ)
USE WAREHOUSE NEXUS_WH;
USE DATABASE NEXUS_DB;
USE SCHEMA NEXUS_SC;

-- Create SESSIONS table
CREATE TABLE IF NOT EXISTS SESSIONS (
    ID INTEGER IDENTITY PRIMARY KEY,
    PRODUCT_IDEA TEXT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'processing',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create ANALYSIS_RESULTS table
CREATE TABLE IF NOT EXISTS ANALYSIS_RESULTS (
    ID INTEGER IDENTITY PRIMARY KEY,
    SESSION_ID INTEGER NOT NULL,
    PERSONAS TEXT, -- JSON string
    OPINIONS TEXT, -- JSON string
    SUMMARY TEXT,
    SENTIMENT_BREAKDOWN TEXT, -- JSON string
    MARKET_POTENTIAL VARCHAR(50),
    CONFIDENCE_SCORE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS(ID)
);
-- Note: Standard Snowflake tables do not support CREATE INDEX.
-- For performance tuning, consider CLUSTER BY, e.g.:
-- ALTER TABLE SESSIONS CLUSTER BY (CREATED_AT);
-- ALTER TABLE ANALYSIS_RESULTS CLUSTER BY (SESSION_ID, CREATED_AT);
